version: "3"

services:
  copa_db:
    image: kartoza/postgis:11.5-2.5
    volumes:
      # New storage location
      - postgres_data:/var/lib/postgresql
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=copa
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      # - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
      - "25432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"
  copa_api:
    build: .
    command: >
      sh -c "
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/copa
    environment:
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DB_PORT=5432
      - DB_HOST=copa_db
    restart: on-failure
    env_file:
      - ./copa/.env
    depends_on:
      copa_db:
        condition: service_healthy
    ports:
      - 8000:8000
  
volumes:
    postgres_data:

networks:
  default:
    external:
      name: copa_net
