# Generated by Django 3.0.6 on 2021-04-24 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativefields',
            name='cooperative',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cooperative_fields', to='cooperative.Cooperative'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cooperativefields',
            name='field_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cooperativefields',
            name='placeholder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cooperativemeta',
            name='key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cooperativemeta',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
