# Generated by Django 3.0.6 on 2021-04-24 14:35

import copa.utils.app_utils.generators
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooperative', '0005_auto_20210424_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(default=copa.utils.app_utils.generators.id_generater, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('identity_card', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=50)),
                ('dob', models.DateField(null=True)),
                ('maritual_status', models.CharField(choices=[('Married', 'M'), ('Single', 'S'), ('Divorsed', 'D')], max_length=50)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cooperative.Cooperative')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberMeta',
            fields=[
                ('id', models.CharField(default=copa.utils.app_utils.generators.id_generater, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_meta', to='cooperative.Member')),
            ],
            options={
                'verbose_name_plural': 'MemberMeta',
            },
        ),
        migrations.CreateModel(
            name='MemberField',
            fields=[
                ('id', models.CharField(default=copa.utils.app_utils.generators.id_generater, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('field_type', models.CharField(blank=True, max_length=255, null=True)),
                ('select_options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('is_required', models.BooleanField(default=False)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
