# Generated by Django 3.0.6 on 2021-04-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0006_member_memberfield_membermeta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': 'Members'},
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('cooperative', 'identity_card')},
        ),
    ]
