# Generated by Django 3.0.6 on 2021-04-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0007_auto_20210425_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='member',
            name='maritual_status',
        ),
    ]
