# Generated by Django 3.0.6 on 2021-05-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0008_auto_20210426_0835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberfield',
            options={'verbose_name_plural': 'MemberFields'},
        ),
        migrations.AlterField(
            model_name='member',
            name='identity_card',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='memberfield',
            name='field_type',
            field=models.CharField(blank=True, choices=[('text', 'text'), ('checkbox', 'checkbox'), ('number', 'number'), ('email', 'email'), ('date', 'date')], max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='membermeta',
            unique_together={('member', 'key')},
        ),
    ]
