# Generated by Django 3.0.6 on 2021-05-17 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0009_auto_20210504_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberfield',
            name='cooperative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.Cooperative'),
        ),
    ]
