# Generated by Django 3.0.6 on 2021-05-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0011_member_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'M'), ('Female', 'F'), ('None', 'None')], default=None, max_length=50, null=True),
        ),
    ]
