# Generated by Django 3.0.6 on 2021-05-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0012_auto_20210531_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'M'), ('Female', 'F'), ('Gabo', 'Gabo'), ('Gore', 'Gore'), ('None', 'None')], default=None, max_length=50, null=True),
        ),
    ]
