# Generated by Django 3.0.6 on 2021-06-02 09:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0013_auto_20210531_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
