# Generated by Django 3.0.6 on 2021-06-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0014_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
