# Generated by Django 3.0.6 on 2021-06-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0015_auto_20210602_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberfield',
            name='key',
            field=models.CharField(max_length=255),
        ),
    ]
