# Generated by Django 3.0.6 on 2021-09-08 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooperative', '0016_auto_20210614_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperative',
            name='creator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cooperatives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
