# Generated by Django 3.0.6 on 2021-09-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0018_member_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Gabo', 'Gabo'), ('Gore', 'Gore'), ('None', 'None')], default=None, max_length=50, null=True),
        ),
    ]
