# Generated by Django 3.0.6 on 2021-09-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0019_auto_20210908_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
