# Generated by Django 3.0.6 on 2021-09-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0020_auto_20210908_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberfield',
            name='field_type',
            field=models.CharField(blank=True, choices=[('text', 'text'), ('checkbox', 'checkbox'), ('radio', 'radio'), ('number', 'number'), ('email', 'email'), ('date', 'date')], max_length=255, null=True),
        ),
    ]
