# Generated by Django 3.0.6 on 2021-09-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0021_auto_20210908_1134'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set(),
        ),
    ]
