# Generated by Django 3.2.6 on 2021-09-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0022_auto_20210908_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='code',
            field=models.IntegerField(default=1),
        ),
    ]
