# Generated by Django 3.2.6 on 2021-09-13 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0023_member_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='code',
        ),
    ]
