# Generated by Django 3.2.6 on 2021-09-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0025_alter_member_identity_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
