# Generated by Django 3.2.6 on 2021-09-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0026_alter_member_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Gabo', 'Gabo'), ('Gore', 'Gore'), ('', '')], default=None, max_length=50, null=True),
        ),
    ]
