# Generated by Django 3.0.6 on 2022-10-13 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0028_auto_20220929_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enabledservices',
            name='subscription_id',
        ),
        migrations.AddField(
            model_name='member',
            name='kudi_books_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enabledservices',
            name='cooperative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_services', to='cooperative.Cooperative'),
        ),
        migrations.AlterField(
            model_name='enabledservices',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='enabledservices',
            name='subscription_status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive'), ('expired', 'expired'), ('', '')], default='active', max_length=255, null=True),
        ),
    ]
