# Generated by Django 3.0.6 on 2022-10-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0029_auto_20221013_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
        migrations.AddField(
            model_name='member',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
