# Generated by Django 3.2.15 on 2022-11-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0030_auto_20221031_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='verification_token_expires_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
