# Generated by Django 3.2.15 on 2022-11-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0031_auto_20221101_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
