# Generated by Django 3.0.6 on 2021-04-21 18:51

import copa.utils.app_utils.generators
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOtherField',
            fields=[
                ('id', models.CharField(default=copa.utils.app_utils.generators.id_generater, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('placeholder', models.CharField(max_length=255)),
                ('field_type', models.CharField(max_length=255)),
                ('select_options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(default=copa.utils.app_utils.generators.id_generater, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=100, null=True, unique=True)),
                ('email', models.EmailField(max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(auto_now_add=True, null=True)),
                ('image', models.CharField(blank=True, default='https://res.cloudinary.com/julien/image/upload/v1594986765/user-avatar_nch70m.png', max_length=150, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('email'), nulls_last=True)],
            },
        ),
    ]
