# Generated by Django 3.0.6 on 2022-09-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210421_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kudibooks_user_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
