# Generated by Django 3.2.15 on 2022-11-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
