# Generated by Django 3.2.15 on 2022-11-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_alter_invoice_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_transfer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_transferred',
            field=models.BooleanField(default=False),
        ),
    ]
