# Generated by Django 3.0.6 on 2021-05-25 09:59

import copa.utils.app_utils.generators
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooperative', '0011_member_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productivity',
            fields=[
                ('id', models.CharField(default=copa.utils.app_utils.generators.id_generater, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('unity', models.IntegerField()),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.Cooperative')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.Member')),
            ],
            options={
                'verbose_name_plural': 'Productivity',
            },
        ),
        migrations.CreateModel(
            name='ProductivityField',
            fields=[
                ('id', models.CharField(default=copa.utils.app_utils.generators.id_generater, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('field_type', models.CharField(blank=True, choices=[('text', 'text'), ('checkbox', 'checkbox'), ('number', 'number'), ('email', 'email'), ('date', 'date')], max_length=255, null=True)),
                ('select_options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('is_required', models.BooleanField(default=False)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('productivity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Productivity')),
            ],
            options={
                'verbose_name_plural': 'ProductivityFields',
            },
        ),
        migrations.CreateModel(
            name='ProductivityMeta',
            fields=[
                ('id', models.CharField(default=copa.utils.app_utils.generators.id_generater, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('prod_type', models.CharField(choices=[('Byinjiye', 'Byinjiye'), ('Byasohotse', 'Byasohotse')], max_length=100)),
                ('key', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('productivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_meta', to='stock.Productivity')),
            ],
            options={
                'verbose_name_plural': 'ProductivityMeta',
                'unique_together': {('productivity', 'key')},
            },
        ),
    ]
