# Generated by Django 3.0.6 on 2021-05-26 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0011_member_gender'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productivityfield',
            name='productivity',
        ),
        migrations.AddField(
            model_name='productivity',
            name='price_per_unity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='productivityfield',
            name='cooperative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.Cooperative'),
        ),
        migrations.AlterField(
            model_name='productivity',
            name='unity',
            field=models.CharField(blank=True, choices=[('kg', 'kg')], default='kg', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productivitymeta',
            name='prod_type',
            field=models.CharField(choices=[('Byinjiye', 'Byinjiye'), ('Byasohotse', 'Byasohotse'), ('Ntacyo', 'Ntacyo')], max_length=100),
        ),
    ]
