# Generated by Django 3.0.6 on 2021-05-31 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0013_auto_20210531_0928'),
        ('stock', '0002_auto_20210526_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivity',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_productivity', to='cooperative.Member'),
        ),
        migrations.AlterField(
            model_name='productivity',
            name='price_per_unity',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productivity',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
