# Generated by Django 3.0.6 on 2021-06-14 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0015_auto_20210602_0926'),
        ('stock', '0003_auto_20210531_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivity',
            name='cooperative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity', to='cooperative.Cooperative'),
        ),
    ]
