# Generated by Django 3.0.6 on 2021-09-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20210615_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productivity',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Productivity'},
        ),
    ]
