# Generated by Django 3.2.6 on 2021-09-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20210908_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivity',
            name='unity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productivityfield',
            name='field_choice',
            field=models.CharField(blank=True, choices=[('percentage', 'percentage'), ('francsadd', 'francsadd'), ('francsremove', 'francsremove'), ('none', 'none')], default='none', max_length=255, null=True),
        ),
    ]
