# Generated by Django 3.2.6 on 2021-09-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20210912_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivityfield',
            name='field_choice',
            field=models.CharField(blank=True, choices=[('percentage', 'percentage'), ('francs', 'francs'), ('francsadd', 'francsadd'), ('francsremove', 'francsremove'), ('none', 'none')], default='none', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productivityfield',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
