# Generated by Django 3.2.6 on 2021-09-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20210912_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivity',
            name='unity',
            field=models.CharField(blank=True, default='kg', max_length=50, null=True),
        ),
    ]
