# Generated by Django 3.2.6 on 2021-09-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_alter_productivityfield_field_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productivity',
            name='message_status',
            field=models.BooleanField(default=False),
        ),
    ]
