# Generated by Django 3.2.6 on 2021-09-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_productivity_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivityfield',
            name='key',
            field=models.CharField(max_length=255),
        ),
    ]
